"""
layout_spec.py

Dataclass definitions and parser for layout spec files (YAML or JSON).

A layout spec is an ordered list of *segment* definitions. Each segment
describes a region of the final payload and how its bytes are produced.

Supported segment types (mutually exclusive):

    until_offset    — pad with pad_byte up to the given offset
    at_offset       — write a fixed value at an exact offset
    dword           — a raw 32-bit value (paired with at_offset)
    repeat          — repeat a single byte N times
    bytes_file      — raw bytes loaded from a file
    raw_bytes       — inline hex or list of ints
    computed        — dynamically generated bytes via registry function

All integer fields accept Python int literals or hex strings ("0x41").
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _to_int(val: Any) -> int:
    if isinstance(val, int):
        return val
    if isinstance(val, str):
        return int(val, 0)
    raise TypeError(f"Cannot convert {val!r} to int")


def _to_bytes_val(val: Any) -> int:
    """Convert a single byte value (int or hex string) to an int 0-255."""
    v = _to_int(val)
    if not (0 <= v <= 255):
        raise ValueError(f"Byte value out of range: {v}")
    return v


# ---------------------------------------------------------------------------
# Segment definitions
# ---------------------------------------------------------------------------

@dataclass
class PadSegment:
    """Pad with *pad_byte* until *until_offset* is reached."""
    name: str
    until_offset: int
    pad_byte: int = 0x41  # 'A'


@dataclass
class AtOffsetSegment:
    """Write a fixed dword (or raw bytes) at an exact offset."""
    name: str
    at_offset: int
    dword: int | None = None          # 32-bit value
    endian: str = "little"            # "little" | "big"
    raw_bytes: bytes | None = None    # alternative to dword


@dataclass
class RepeatSegment:
    """Repeat a single byte *count* times."""
    name: str
    byte: int
    count: int


@dataclass
class BytesFileSegment:
    """Load raw bytes from *path*."""
    name: str
    path: str                         # resolved relative to spec file dir


@dataclass
class RawBytesSegment:
    """Inline raw bytes (hex string like 'deadbeef' or list of ints)."""
    name: str
    data: bytes


@dataclass
class ComputedSegmentDef:
    """Specification for a computed segment."""
    function: str
    args: dict[str, Any] = field(default_factory=dict)


@dataclass
class ComputedSegment:
    """Bytes generated by a registered computation function."""
    name: str
    computed: ComputedSegmentDef


# Union type for all segments
Segment = PadSegment | AtOffsetSegment | RepeatSegment | BytesFileSegment | RawBytesSegment | ComputedSegment


# ---------------------------------------------------------------------------
# Layout spec
# ---------------------------------------------------------------------------

@dataclass
class LayoutSpec:
    """
    Ordered list of segments describing a complete payload layout.

    Attributes:
        segments: Ordered segment definitions.
        badchars: Bytes forbidden in the final payload.
        expected_total_size: Optional sanity-check on final payload length.
        source_dir: Directory of the spec file (for resolving bytes_file paths).
    """
    segments: list[Segment]
    badchars: bytes = b""
    expected_total_size: int | None = None
    source_dir: Path = field(default_factory=Path.cwd)


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

class LayoutSpecParser:
    """Parse a YAML or JSON layout spec file into a :class:`LayoutSpec`."""

    def parse_file(self, path: str | Path) -> LayoutSpec:
        p = Path(path)
        if not p.exists():
            raise FileNotFoundError(f"Layout spec not found: {p}")
        raw = p.read_text(encoding="utf-8")
        data = self._load(raw, suffix=p.suffix)
        return self._parse(data, source_dir=p.parent)

    def parse_string(self, text: str, source_dir: Path | None = None) -> LayoutSpec:
        data = self._load(text, suffix=".json")
        return self._parse(data, source_dir=source_dir or Path.cwd())

    # ------------------------------------------------------------------

    def _load(self, text: str, suffix: str) -> dict:
        if suffix in (".yaml", ".yml"):
            try:
                import yaml  # type: ignore
                return yaml.safe_load(text)
            except ImportError:
                raise ImportError(
                    "PyYAML is required to parse YAML layout specs. "
                    "Install it with: pip install pyyaml"
                )
        else:
            return json.loads(text)

    def _parse(self, data: dict, source_dir: Path) -> LayoutSpec:
        badchars_raw = data.get("badchars", [])
        if isinstance(badchars_raw, str):
            # hex string: "000a0d"
            badchars = bytes.fromhex(badchars_raw)
        elif isinstance(badchars_raw, list):
            badchars = bytes(_to_bytes_val(b) for b in badchars_raw)
        else:
            badchars = b""

        expected_total_size: int | None = None
        if "expected_total_size" in data:
            expected_total_size = _to_int(data["expected_total_size"])

        raw_segments: list[dict] = data.get("segments", [])
        segments: list[Segment] = [
            self._parse_segment(s, source_dir) for s in raw_segments
        ]

        return LayoutSpec(
            segments=segments,
            badchars=badchars,
            expected_total_size=expected_total_size,
            source_dir=source_dir,
        )

    def _parse_segment(self, s: dict, source_dir: Path) -> Segment:
        name: str = s.get("name", "<unnamed>")

        if "until_offset" in s:
            return PadSegment(
                name=name,
                until_offset=_to_int(s["until_offset"]),
                pad_byte=_to_bytes_val(s.get("pad_byte", 0x41)),
            )

        if "at_offset" in s:
            seg = AtOffsetSegment(
                name=name,
                at_offset=_to_int(s["at_offset"]),
                endian=s.get("endian", "little"),
            )
            if "dword" in s:
                seg.dword = _to_int(s["dword"])
            elif "raw_bytes" in s:
                seg.raw_bytes = self._parse_inline_bytes(s["raw_bytes"])
            else:
                raise ValueError(f"Segment '{name}' has at_offset but no dword/raw_bytes")
            return seg

        if "repeat" in s:
            r = s["repeat"]
            return RepeatSegment(
                name=name,
                byte=_to_bytes_val(r["byte"]),
                count=_to_int(r["count"]),
            )

        if "bytes_file" in s:
            return BytesFileSegment(
                name=name,
                path=str(source_dir / s["bytes_file"]),
            )

        if "raw_bytes" in s:
            return RawBytesSegment(
                name=name,
                data=self._parse_inline_bytes(s["raw_bytes"]),
            )

        if "computed" in s:
            c = s["computed"]
            return ComputedSegment(
                name=name,
                computed=ComputedSegmentDef(
                    function=str(c["function"]),
                    args=dict(c.get("args", {})),
                ),
            )

        raise ValueError(f"Segment '{name}' has no recognized type key")

    @staticmethod
    def _parse_inline_bytes(val: Any) -> bytes:
        if isinstance(val, str):
            return bytes.fromhex(val.replace(" ", ""))
        if isinstance(val, list):
            return bytes(_to_bytes_val(b) for b in val)
        raise TypeError(f"Cannot parse inline bytes from {val!r}")
